### ISSUE TITLE
Broken exit from development/edit mode

### ISSUE THREAD

**Issue by mistafunk** [Esri/pyprt#14]
Leaving the development mode has these issues (reproduced on Linux):
* `pip uninstall pyprt` reports an error and does not uninstall the editable pyprt (a workaround is to use `setup.py development -u`): 
> (pyprt) [shaegler@zrh-rascal pyprt]$ pip uninstall pyprt
> Found existing installation: pyprt 1.0.0b1
> Not uninstalling pyprt at /home/shaegler/esri/dev/git/pyprt, outside environment  /home/shaegler/.local/share/virtualenvs/pyprt-bVb_FBxx
> Can't uninstall 'pyprt'. No files were found to uninstall.

* running `setup.py clean` deletes *all* files from the pyprt source directory not just the temporary ones installed by `pip install -e .`:
> (pyprt) [shaegler@zrh-rascal pyprt]$ python setup.py clean
> running clean
> removing 'build/temp.linux-x86_64-3.6' (and everything under it)
> removing './pyprt/__init__.py'
> removing './pyprt/pyprt/__init__.py'
> removing './pyprt/pyprt/lib' (and everything under it)
> removing './pyprt/pyprt/bin' (and everything under it)
> removing './pyprt/pyprt_utils/__init__.py'
> removing './pyprt/pyprt_utils/pyprt_utils.py'
> removing './pyprt/pyprt_arcgis/__init__.py'
> removing './pyprt/pyprt_arcgis/pyprt_arcgis.py'
> removing './pyprt.egg-info/record_setup_develop_files.txt'

**Comment by clechot** [comment]
Concerning the second point, this happens when the build folder is not empty before running `pip install -e .`. If we don't clean the build folder before running `pip install -e .`, everything in this build folder will be copied (and recorded in the record_setup_development_files.txt) to the pyprt directory (and the pyprt_utils.py and pyprt_arcgis.py as well). To be sure, `setup.py clean --all` should be called before `pip install -e .`. We'll think about a more sustainable solution.

**Comment by mistafunk** [comment]
The first issue seems to be a problem of that specific machine/linux distro/python distro.
The second issue is fundamental to setuptools.

I've added an explicit clean call to the instructions to reduce the risk of users running into it.

I'm closing this as we cannot do much more at the moment, hopefully pip development mode learns to better handle native extensions in future releases.
