### ISSUE TITLE
I installed it successfully, but an error occurred when I ran it.How should I solve it

### ISSUE THREAD

**Issue by caichunbing** [Esri/pyprt#72]
[error] failed to load library: error while loading library 'C:\ProgramData\Anaconda3\lib\site-packages\pyprt\pyprt\lib\com.esri.prt.unreal.dll'

**Comment by mistafunk** [comment]
This error message is triggered when PyPRT fails to load an included encoder.

In your case, PyPRT was not able to load the Unreal Engine encoder, likely due to missing dependencies. However, your python app should still work fine if you do not need to encode/export to Unreal Engine.

If you need the Unreal Engine encoder, please install Unreal Engine or just the Unreal Engine runtimes (https://unrealstudio.epicgames.com/UE4PrereqSetup_x64.exe). Then com.esri.prt.unreal.dll should load fine.

**Comment by mistafunk** [comment]
@caichunbing I'm closing this now - feel free to reopen if you need further assistance. :-)
